apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: todo-app
spec:

  selector:
    app: backend

  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30080

  type: NodePort